apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: learninglocker
 namespace: ll2
 annotations:
  nginx.ingress.kubernetes.io/rewrite-target: /
  kubernetes.io/ingress.class: "nginx"
spec:
 rules:
 - http:
    paths:
    - path: /ui
      backend:
       serviceName: ui
       servicePort: 3000
    - path: /api
      backend:
       serviceName: api
       servicePort: 8080
    - path: /xapi
      backend:
       serviceName: xapi
       servicePort: 8081