apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
parameters:
  skuName: Standard_RAGRS
  storageAccount: STORAGE_ACCOUNT_IN_K8S_MC_RESOURCE_GROUP
  location: westeu