apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: ll2
  name: worker
spec:
  selector:
    matchLabels:
      llappName: worker
  serviceName: worker
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      namespace: ll2
      labels:
        llappName: worker
    spec:
      containers:
      - command: [ "/bin/sh", "-c"]
        args:
        - node worker/dist/server
        env:
        - name: NODE_ENV
          value: production
        - name: SITE_URL
          value: USED_FOR_EMAILS.COM
        - name: APP_SECRET
          value: T!7L@lk*cs$Z'Z)mn@ey(g`s+x9G-pQ
        - name: MONGODB_PATH
          value: $MONGO_DB_CONNECTION_STRING
        - name: REDIS_HOST
          value: redis.ll2.svc.cluster.local
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        - name: REDIS_PREFIX
          value: LEARNINGLOCKER
        - name: COLOR_LOGS
          value: "true"
        - name: SMTP_HOST
          value: ""
        - name: SMTP_PORT
          value: ""
        - name: SMTP_SECURED
          value: ""
        - name: SMTP_USER
          value: ""
        - name: SMTP_PASS
          value: ""
        - name: QUEUE_PROVIDER
          value: REDIS
        - name: QUEUE_NAMESPACE
          value: DEV
        - name: FS_REPO
          value: local
        - name: LOG_MIN_LEVEL
          value: silly
        image: $YOUR_CONTAINER_REGISTRY/learninglocker2-app:dev
        name: worker
        resources: {}
        volumeMounts:
        - mountPath: /opt/learninglocker/storage
          name: worker-claim
      restartPolicy: Always
      imagePullSecrets:
        - name:  acr-auth
  volumeClaimTemplates:
  - metadata:
      name: worker-claim
    spec:
      storageClassName: azurefile
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 5Gi
